### ISSUE TITLE
Laravel 5.5 Package Auto-Discovery

### ISSUE THREAD

**Issue by jonagoldman** [ernysans/laraworld#6]
Will this package add support for Laravel 5.5?

**Comment by ernysans** [comment]
Hi @jonagoldman. I'm too busy to work on this. But you can send a PR with this support and I will push a new release.

**Comment by jonagoldman** [comment]
Will try to do that.

**Comment by ernysans** [comment]
@jonagoldman I just released v1.0.2 with your changes.
Thank you.
